### ISSUE TITLE
[Question] About different layers

### ISSUE THREAD

**Issue by sesky4** [bartofzo/NativeTrees#7]
Hi, thanks for this great project.

In my case, I want to query nearest N objects with certain type ( eg. tree / house / people ).

Should I build a new tree for each type OR use a single tree and store the type enum into tree node ?

Thanks !

**Comment by bartofzo** [comment]
For nearest neighbours the easiest would be to put them all into one tree. Otherwise you'd have to combine multiple queries of different trees to see which one is closest.
I think I would just put Id's in the tree which you can then later map onto the objects themselves. But it really depends on a lot of factors. Try out a couple of scenarios?
